name: Generate Lockfile

on:
  push:
    branches: [main]

jobs:
  generate-lockfile:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies
      run: npm install

    - name: Commit lockfile
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "actions@github.com"
        git add package-lock.json
        git commit -m "Auto-generate lockfile"
        git push
      continue-on-error: true
